version: '3.4'

services:
  seq: 
    image: datalust/seq:latest
    container_name: seq-logs
    restart: always
    environment: 
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  